# Generated by Django 3.2.9 on 2021-11-10 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('BUY', 'COMPRA'), ('SELL', 'VENDA')], max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('daytrade', models.BooleanField()),
                ('mean_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profits.asset')),
            ],
        ),
    ]
