# Generated by Django 3.2.9 on 2021-11-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0002_auto_20211111_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='quantidade_acumulada',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
